# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  install_sdk:
    description: "Install Daml SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          name: Install Daml SDK
          command: |
            curl -sSL https://get.daml.com/ | sh /dev/stdin << parameters.version >>
            # idea from https://circleci.com/docs/2.0/env-vars/
            >> $BASH_ENV echo 'export PATH="$HOME/.daml/bin:$PATH"'

jobs:
  simple-daml-test:
    parameters:
      daml_sdk_version: 
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - install_sdk:
          version: << parameters.daml_sdk_version >>
      - run:
          name: "daml test"
          command: "daml test"

workflows:
  simple-daml-test-workflow:
    jobs:
      - simple-daml-test:
          daml_sdk_version: "2.3.2"
